= Terraform MySQL module
Author Name <sergey.mahnovsky@abcfitness.com>
V0.1

:imagesdir: ./docs
:iconsdir: ./docs
:toc:
:toclevels: 3

This repository contains Terraform module for MySQL users and privileges management. Also using this module you can create new databases

== Features

* Central users management
* Multiple Databases creation
* Manage users from local variable file
* Manage users from AWS Secret manager
* Manage user privileges based on prepared map
* Support AWSAuthenticationPlugin for user authentication. Make sure that selected DB instance type https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/UsingWithRDS.IAMDBAuth.html[support] IAM database authentication


== Learn

This repository is enhanced with https://pre-commit.com/[pre-commit] development framework which launches on every
commit. All required tooling to work with this repository can be installed using Makefile on Linux and MacOS user
machines. It is assumes that some core components on user machine have a default configuration, ie.: .profile and
user PATH variables for GoLang as an example.

Run below commands:

[source,bash]
----
make all
pre-commit run --all-files
----


== Repository folder
* *examples/test* - working examples
* *modules/aurora* - module for RDS cluster with Aurora instance

Use winebarrel MySQL https://registry.terraform.io/providers/winebarrel/mysql/1.10.5[provider]

== Usage
* clone repository
* cd examples/test
* edit variables as required and provide valid user list in variable or AWS Secret manager. Template for user definition you can find in examples/test/variables.tf. In AWS Secret manager valid users format is:

[source,yaml]
----
[
  {
    "username": "user1",
    "password": "pass1",
    "host": "any",
    "role": "qa"
    "database" : ["*"]
  },
  {
    "username": "user2",
    "password": "pass2",
    "host": "vpn",
    "role": "dev"
    "database" : ["*"]
  }
]
----

* run terraform init
* run terraform plan to check planned actions and states
* run terraform apply to apply changes